name: 'E2E Tests'
on:
  workflow_dispatch:
  push:
jobs:
  run-e2e-tests:
    name: 'E2E Tests'
    runs-on: ubuntu-latest
    timeout-minutes: 35
    container:
      image: cypress/included:10.4.0
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Yarn Install
        run: yarn
      - name: Debugging with ssh
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: AtofStryker
      - name: run cypress
        run: cypress run --browser firefox