name: 'E2E Tests'
on:
  workflow_dispatch:
  push:
jobs:
  run-e2e-tests:
    name: 'E2E Tests'
    runs-on: ubuntu-latest
    timeout-minutes: 35
    container:
      image: cypress/included:10.4.0
      options: --user root
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Symlink firefox
        run : mv -f /opt/firefox/firefox /usr/bin/firefox
      - name: echo path
        run: echo $PATH
      - name: add opt to path
        run: export PATH="/opt/firefox:$PATH"
      - name: echo path
        run: echo $PATH
      - name: list permissions
        run:  ls -al /usr/bin
      - name: install
        run: yarn
      - name: run cypress
        run: DEBUG=cypress:server:browsers:firefox cypress run --browser firefox