name: 'E2E Tests'
on:
  workflow_dispatch:
  push:
jobs:
  run-e2e-tests:
    name: 'E2E Tests'
    runs-on: ubuntu-latest
    timeout-minutes: 35
    container:
      image: cypress/included:10.4.0
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Yarn Install
        run: yarn
      - name: Check installed binaries
        run : ls -al /usr/bin
      - name: run cypress
        run: cypress run --browser="/opt/firefox/firefox"